@startuml clases

class main{
    + void main()
}

class AlfaYBeta{
    + enum Estado
    - boolean iniciado
    - long alfa
    - long beta
    - long inicio
    - boolean sinRestriccion
    + AlfaYBeta(long alfa, long beta)
    + AlfaYBeta()
    + setAlfaYBeta(long alfa, long beta)
    + setInicio(long inicio)
    + long getInicio()
    + long getBeta()
    + long getAlfa()
    + iniciar()
    + Estado verificar()
    + long getTiempoExcedido()
}

class AtencionAgente{
    - NumeroDeAgente agente
    - MonitorInterface monitor
    + AtencionAgente(NumeroDeAgente agente, MonitorInterface monitor)
    + void run()
    + String toString()
}

class Cancelacion{
    - MonitorInterface monitor
    + Cancelacion(MonitorInterface monitor)
    + void run()
    + String toString()
}

class ConfirmacionYPago{}

class EntradaDeClientes{}

class Log{}

class Monitor{}

interface MonitorInterface{}

class NumeroDeAgente{}

class OutTHreadFactory{}

class Politica{}

class PoliticaAgenciaVuelo{}

class RedPetri{}

@enduml