@startuml secuencia
!pragma teoz true
' Definicion de participantes
participant Hilo1
participant Hilo2
participant Monitor
participant Mutex
participant Red_de_petri
participant Colas 
participant Politicas
participant SensibilizadoConTiempo

' Secuencia
'' El hilo intenta disparar una Transicion
activate Hilo1
Hilo1 -> Monitor : dispararTransicion(Tn)
activate Monitor
Monitor -> Mutex : acquire()
activate Mutex
Mutex --> Monitor
deactivate Mutex

Monitor -> Monitor : k=true
activate Monitor
deactivate Monitor

loop k==true
    Monitor -> Red_de_petri : disparar(Tn)
    activate Red_de_petri
    & Red_de_petri -> Red_de_petri : estaSensibilizado()
    Red_de_petri -> SensibilizadoConTiempo : getVentana(Tn)
    activate SensibilizadoConTiempo
    SensibilizadoConTiempo --> Red_de_petri : ventana
    
    alt ventana == true
        alt esperando == false
            Red_de_petri -> SensibilizadoConTiempo : setNuevoTimeStamp()
            deactivate SensibilizadoConTiempo
            Red_de_petri -> Red_de_petri : se_disparo = true
        else esperando == true
            Red_de_petri -> Red_de_petri : se_disparo = false
        end
        
    else ventana == false
        Red_de_petri -> SensibilizadoConTiempo : antesDeLaVentana()
        activate SensibilizadoConTiempo
        SensibilizadoConTiempo --> Red_de_petri : antes
        deactivate SensibilizadoConTiempo
        alt antes == true
            Red_de_petri -> SensibilizadoConTiempo : esperarAlfa()
            activate SensibilizadoConTiempo
            deactivate SensibilizadoConTiempo
            Red_de_petri -> Red_de_petri : sleep
        else antes == false
            Red_de_petri -> Red_de_petri : se_disparo = false    
        end 
    end

    Red_de_petri --> Monitor : se_disparo
    
    alt se_disparo == true
        Monitor -> Red_de_petri : sensibilizadas()
        Red_de_petri --> Monitor : Vs
        Monitor -> Colas : quienesEstan()
        activate Colas
        Colas --> Monitor : Vc
        deactivate Colas
        Monitor -> Monitor : m = Vs and Vc
        Red_de_petri -> SensibilizadoConTiempo : resetEsperando()
        activate SensibilizadoConTiempo
        deactivate SensibilizadoConTiempo
        alt m<>0 (Hay hilos esperando)
            Monitor-> Red_de_petri : cualDisparar(m)
            & Red_de_petri -> Politicas : cualDisparar(m)
            activate Politicas
            Politicas --> Monitor : NumeroTransicion
            deactivate Politicas
            Monitor --> Hilo1 : Sale del monitor
            Red_de_petri -> SensibilizadoConTiempo : setNuevoTimestamp()
            activate SensibilizadoConTiempo
            deactivate SensibilizadoConTiempo 
            deactivate Hilo1
            Monitor -> Colas : release()
            activate Colas
            Colas --> Monitor
            deactivate Colas
            Monitor --> Hilo2 : se activa el hilo
            activate Hilo2
        else m == 0 (No hay hilos esperando)
            Monitor -> Monitor : k=false
            activate Monitor
            deactivate Monitor
        end
    else se_disparo == false
        Monitor -> Mutex : release()
        activate Mutex
        Mutex --> Monitor
        deactivate Mutex
        Monitor-> Colas : acquire()
        activate Colas
        Colas --> Monitor
        deactivate Colas

    end
    Hilo2 -> Monitor : continua ejecucion
end
deactivate Hilo2


@enduml